name: 'Run LanguageTool with reviewdog'
description: '🐶 Run LanguageTool with reviewdog on pull requests to improve code review experience.'
author: 'haya14busa'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
  ### Flags for reviewdog ###
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  filter:
    description: 'reviewdog filter.'
    default: 'added'
  reporter:
    description: 'Reporter of reviewdog command [github-pr-check,github-pr-review].'
    default: 'github-pr-check'
  ### Flags for target file ###
  patterns:
    description: 'Space separated target file glob patterns. https://github.com/haya14busa/ghglob'
    default: '**/*.md **/*.txt'
  ### Flags for LanguageTool ###
  # Ref: https://languagetool.org/http-api/swagger-ui/#!/default/post_check
  language:
    description: 'language of LanguageTool'
    default: 'auto'
  mother_tongue:
    description: 'Mother tongue of the author'
  enabled_rules:
    description: 'comma separeted enabledRules of LanguageTool'
  disabled_rules:
    description: 'comma separeted disabledRules of LanguageTool'
  enabled_categories:
    description: 'comma separeted enabledCategories of LanguageTool'
  disabled_categories:
    description: 'comma separeted disabledCategories of LanguageTool'
  enabled_only:
    description: 'enabledOnly of LanguageTool'
  # tool options
  rule_files:
    description: 'Additional rules to be used as input for LanguageTool'
  concurrent:
    description: 'Number of concurrent checks to be performed at the server'
  verbose:
    description: 'Verbose debug output besides check results'

  custom_api_endpoint:
    description: 'Custom API endpoint of LanguageTool server. e.g. https://languagetool.org/api'
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'check-square'
  color: 'blue'
